Repository Stock-FCIT/client, pull requests merged in 2023-04, with the labels that each got.

#40 Fix displaing of pictures
  src/Pages/Details/Details.jsx
  src/components/Item/Item.jsx
Labels: bug

#43 Linked Reg and Log with backend
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/Pages/Main/Main.jsx
  src/Pages/Main/Main.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Input/Input.module.scss
  src/components/Login/Login.jsx
  src/components/Login/Login.module.scss
  src/components/Register/Register.jsx
  src/components/UserMenu/UserMenu.jsx
  src/components/UserMenu/UserMenu.module.scss
  src/components/store/UserStore.js
  src/http/index.js
  src/http/userAPI.js
  src/images/userPhoto.png
  src/index.js
Labels: feature

#45 Fixed displaying of images
  src/Pages/Details/Details.scss
  src/components/Item/Item.scss
  src/index.js
  src/store/UserStore.js
Labels: bug

#52 Autofill with available information
  src/Pages/UserPage/UserPage.jsx
  src/components/EditInfo/EditInfo.jsx
Labels: feature

#55 Added PageNotFound
  src/App.js
  src/App.scss
  src/Pages/Details/Details.scss
  src/Pages/NotFound/NotFound.jsx
  src/Pages/NotFound/NotFound.scss
  src/images/pageNotFound.png
Labels: feature

#60 Fixed visbility of navbar items
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
Labels: fixed bug

#69 favorite datadase
  src/Pages/Main/Main.jsx
  src/Pages/UserPage/UserPage.jsx
  src/components/EditPassword/EditPassword.jsx
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Item/Item.jsx
  src/components/Item/Item.scss
  src/components/UserFavorite/UserFavorite.jsx
  src/components/UserFavorite/UserFavorite.scss
  src/http/favouriteAPI.js
  src/images/favoutiteButton.jsx
  src/images/favoutiteButton.svg
  src/images/liked.svg
Labels: feature
